{{- if .Values.node.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: akernel-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  oss_auths.json: |
{{ .Values.node.secret.oss_auths | toPrettyJson | indent 4 }}

  registry_auths.json: |
{{ .Values.node.secret.registry_auths | toPrettyJson | indent 4 }}
{{- end }}
