apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  admin-password: {{ include "monitor.grafanaAdminPassword" . | quote }}
