{{- if .Values.imagePullSecret }}
{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name | default "acr-secret" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson }}
{{- end }}
{{- end }}
