{{- if and .Values.traefik.enabled .Values.traefik.tls.enabled .Values.traefik.tls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.traefik.tls.secretName | default "traefik-tls" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  module.crt: {{ .Values.traefik.tls.moduleCrt | default "" | b64enc | quote }}
  module.key: {{ .Values.traefik.tls.moduleKey | default "" | b64enc | quote }}
{{- end }}
