apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akernel-dependency-cache
spec:
  storageClassName: csi-local-topology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
